#!/usr/bin/env fish


# navigate to jupyter notes directory
cd $CODES/Jupyter-notes

# start virtual environment
source env/bin/activate.fish

# start clusters for parallel computing & jupyter notebook
ipcluster start & jupyter notebook --no-browser --autoreload --ip=0.0.0.0 && fg
